"""
Config variables are read/write.
"""
from pydantic import BaseModel, Field


class GuildConfig(BaseModel):
    rules_phishing_content: int = Field(2, ge=0, le=2)
    rules_phishing_domain_blacklisted: int = Field(2, ge=0, le=2)
    rules_phishing_domain_heuristic: int = Field(2, ge=0, le=2)
    rules_phishing_embed: int = Field(2, ge=0, le=2)
    rules_selfbot_embed: int = Field(2, ge=0, le=2)
    rules_ping_hidde: int = Field(2, ge=0, le=2)
    rules_ping_roles: int = Field(2, ge=0, le=2)
    rules_ping_users_many: int = Field(2, ge=0, le=2)
    rules_ping_users_few: int = Field(1, ge=0, le=2)
    rules_ping_broad: int = Field(1, ge=0, le=2)
    rules_advertisement_discord_server: int = Field(1, ge=0, le=2)
    rules_emoji_mass: int = Field(0, ge=0, le=2)
    antispam_similar: bool = Field(True)
    antispam_exact: bool = Field(True)
    antispam_token: bool = Field(True)
    antispam_sticker: bool = Field(True)
    antispam_attachment: bool = Field(True)
    overview_modroles: list[int] = Field(default_factory=list, max_items=256)
    overview_dehoisting_enabled: bool = Field(True)
    overview_discordimpersonation_enabled: bool = Field(True)
    slowmode_enabled: bool = Field(True)
    slowmode_exceptions: list[int] = Field(default_factory=list, max_items=256)
    challenge_timeout_enabled: bool = Field(True)
    challenge_interactive_enabled: bool = Field(False)
    challenge_interactive_take_role: bool = Field(False)
    challenge_interactive_role: int = Field(0, ge=0, le=1 << 64)
    challenge_interactive_joinrisk_custom: int = Field(0, ge=0, le=100)
    challenge_interactive_level: int = Field(2, ge=0, le=5)
    challenge_interactive_webpage_splash: str = Field("", max_length=256)
    logging_enabled: bool = Field(False)
    logging_channel: int = Field(0, he=0, le=1 << 64)
    logging_option_join: bool = Field(False)
    logging_downloads_enabled: bool = Field(False)
    workers_enabled: bool = Field(False)
    workers_script: str = Field("", max_length=1024 * 1024)
    bot_custom: str = Field("", max_length=128)
